### PR TITLE
Uads 009/implement login screen

### PR DESCRIPTION
**Pull request by danielle161**
**Issue:**
Implemented both the login screen and the registration screen.

**Solution:**
Created components for login and registration screens.  Implemented correct layout based on wireframes and connected to firebase for authentication.

**Risk:**
Layout might look different depending on screen size.  May need to change what inputs we are taking depending on what information we want to store about the user.  Currently taking their UPI and adding "@aucklanduni.ac.nz" in order to create their email for registration/login.

**Reviewed By:**
Daniel

### CODE REVIEW

**Comment by Dan1224444** [comment]
Looks good, I'll get @Brendan-Z and @jose-vs to review this as they've been working on the other front-end task :)

**Comment by Brendan-Z** [comment]
Yup everything looks good although I'm not much of an expert at firebase :)

**Comment by jose-vs** [comment]
Would it be ok to get the firebase files so I can have it running on my machine. But other than that, the code looks good to me. It might be missing an import for Alert on the login-screen.tsx though I think.

**Review by Dan1224444 — APPROVED** [review]
Seems to be working, some errors in console but that can be fixed later (:

**Review by Brendan-Z — APPROVED** [review]

**Review by jose-vs — APPROVED** [review]
Looks good!

**Pull request merged**
