### PR TITLE
Uads 017/save login state

### PR DESCRIPTION
**Pull request by jose-vs**
**Issue:**
App needed to have dummy screens for home, about, settings, sponsors and authors and to have navigation to those screens when the user has logged in. The login state must also be saved so a user doesn't need to log in again. 

**Solution:**
Implemented dummy screens, navigation to those screens and saving the login state

**Risk:**
This error may be a potential risk but does not seem to be affecting the code at this point 

`o is not a function. (In 'o()', 'o' is undefined)`

**Reviewed By:**
@viresh-oberoi 
@Dan1224444 
@danielle161

### CODE REVIEW

**Review by danielle161 — APPROVED** [review]
LGTM

**Review by Brendan-Z — APPROVED** [review]
LGTM

**Review by viresh-oberoi — COMMENTED** [review]
App runs well, LGTM!

**Review by viresh-oberoi — APPROVED** [review]

**Review by Dan1224444 — APPROVED** [review]
Working as intended, great job!

**Pull request merged**
