### PR TITLE
Implementation of Husky Hook

### PR DESCRIPTION
**Pull request by johnchen383**
**Issue:**
Commits to repositories were not properly formatted by prettier.

**Solution:**
Husky and Lintstage were added to add a pre-commit hook to format commits prior to Git commits

**Risk:**
No risks of note. Would require review to ensure package.json works as required.

**Reviewed By:**
Frontend @Dan1224444 @danielle161 @viresh-oberoi @jose-vs

### CODE REVIEW

**Review by viresh-oberoi — APPROVED** [review]
Tried committing weird indentation changes, it 'prettified' the indentions, and cancelled the commit as there were no other changes made to the file. So, it works as intended and LGTM!

**Review by jose-vs — APPROVED** [review]
LGTM! 👍

**Review by danielle161 — APPROVED** [review]
LGTM

**Comment by Dan1224444** [comment]
I Prove :)

**Review by Dan1224444 — APPROVED** [review]

**Pull request merged**
